### ISSUE TITLE
Publish `adtl` on PyPi

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/adtl#101]
This will allow [InsightBoard](https://github.com/globaldothealth/InsightBoard) to depend on adtl directly in its package installation.

**Comment by pipliggins** [comment]
@abhidg did we do this? I know the install instructions have changed but when I just tried pypi claimed no matching distribution

**Comment by abhidg** [comment]
It was on my list to do - changed the README before that!

**Comment by abhidg** [comment]
@pipliggins I have been trying to push to PyPi with publish-testpypi.yml, it has been failing for some reason

**Comment by abhidg** [comment]
Done! https://pypi.org/project/adtl/
