### ISSUE TITLE
Create default 'if' behaviour for observations

### ISSUE THREAD

**Issue by pipliggins** [globaldothealth/adtl#49]
Currently an 'if' statement has to be written for every observation, which stops a table row being created for the observation if the data recorded is falsey (None, or equivalents). 

Default adtl behaviour should automate this for the OneToMany table, so 'if' statements only need to be used when a departure from normal usage is required, e.g. if an observation should only be displayed where a different observation has also been recorded.

By default, any row where the observation isn't a value described in the 'values' section (i.e. either if it's empty, or a value mapped to NK/None etc.) should not be displayed.

**Comment by abhidg** [comment]
Fixed by f2b3cbe21d709f84a62f71f9602cf0f158dd7e09
