### ISSUE TITLE
Overwriting data

### ISSUE THREAD

**Issue by pipliggins** [globaldothealth/adtl#90]
Cross post from the ISARIC repo issue globaldothealth/isaric#203

**Comment by abhidg** [comment]
I think we can use combinedType settings to apply the appropriate combinator across rows in this block https://github.com/globaldothealth/adtl/blob/main/adtl/__init__.py#L718-L722. Will need to regenerate all data files as set/list combinedType fields would change, which makes sense.

**Comment by pipliggins** [comment]
Yep, that was broadly my thought. Have we actually generated many results files? I know I haven't in a while
